### ISSUE TITLE
Add empty strings or null for sound effects so people know what to edit

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-scrolling-texts#1]
I have yet to sit down and prepare some default effects, but meanwhile please add to mappings a null or empty strings where the sound effects need to be so people can know this feature exists and can edit them.

**Comment by elizeuangelo** [comment]
I added a readme in the condition mappings folder (708ad50fa1d9dab801bb226146a42827a0e00456) to explain the parameters, there is no need to fill empty strings as it wouldnt be explanatory in itself, people still won't understand why there are empty strings in the map.

Also, it would hurt formatting because the second, third and forth elements of the array are entirely optional and can be undefined, and should be undefined in case you dont want to use them.
